### ISSUE TITLE
Dynamic Directive Nesting Issue

### ISSUE THREAD

**Issue by mindontheblink** [GraFiddle/angular-chart#101]
I am using the angularchart directive nested inside another parent directive that I use to generate dynamic chart instances.   This works great with one dynamic instance, but as soon as I create a second instance using the same directive (with angularchart nested inside), my first angular chart's settings (options, dataset, schema) get overridden with those of the new chart's.

I have ensured that the bindings of options, dataset, and schema are unique to the parent directive, yet somehow the angularchart directive referenced in this directive seems to remember all other previous instances defined inside this directive and update them.

What can I do to ensure an angularchart directive nested inside another directive always remains isolated from other instances?  I have tried wrapping the angularchart directive in my own custom directive where I control the one-way bindings and isolate scope -- yet the angular chart bindings still seem to exist at a global level when nested in another directive.

I figured if there were some way I could toggle this (in angular-chart.js):
               
                scope: {
                    dataset: '=',
                    options: '=',
                    schema: '='
                },

to this

                scope: {
                    dataset: '@',
                    options: '@',
                    schema: '@'
                },

in my unique scenario, this might get me on the right track.  This doesn't play nicely with the rest of the code though.

Any help or recommendations regarding this issue would be greatly appreciated!

**Comment by maxklenk** [comment]
Hi @mindontheblink,
first of all, are you using the latest version of angular-chart? The new 0.3.x version came out a few months ago, you can read [here](https://github.com/GraFiddle/angular-chart#upgrade-02x-to-030) how to upgrade from an earlier version. 
Please report back if you still experience this problem or if you have to stick to an older version.

**Comment by mindontheblink** [comment]
Hey @maxklenk  - thanks for the quick reply.

I had just noticed after posting that I am still on 0.2.9.  I will report back after the upgrade.  Sorry!

**Comment by mindontheblink** [comment]
Just upgraded to the latest and made the appropriate changes based on your upgrade guide.  This still appears to be an issue.

**Comment by maxklenk** [comment]
Mmh, angular-chart has an internal service which is create newly for every usage of the directive. Perhaps the angular-chart directive you access is still the same and therefor contains the old data.
The only idea I have is to wrap it with an `ng-if` which hides it at first an then renders the directive when needed.
If it still doesn't work you may add the basics of your custom directive to this [plunker](http://plnkr.co/edit/HpD8l7) so we will be able to look into it.

**Comment by mindontheblink** [comment]
Thanks again for the quick reply!  I will try that and get back to you.

**Comment by mindontheblink** [comment]
I forked your plunk and created this, which is working.

http://plnkr.co/edit/M5IkNKdJaNnPjYeu1ZIb

This is not 100% of what I am doing.  In my application, I am dynamically injecting the custom-template instances into the DOM, (adding the directive to angular's $templateCache).  I will try to add this to my plunk tomorrow or Monday and see if it is reproducible here.

Thanks again for bearing with me.

**Comment by mindontheblink** [comment]
I morphed the above plunker into something very close to what I am doing.  I was still not able to recreate.  I will have to step back into my code and diff against this basic skeleton.  Mark this as non-issue for now until you hear back.  

http://plnkr.co/edit/gTMUjVw9sx8JnVeqh1il?p=preview

**Comment by maxklenk** [comment]
Ok, I hope you find the difference.

**Comment by mindontheblink** [comment]
Found the difference.  It was my fault -- sorry I commented here without doing more research.   You can go ahead and mark this as a non-issue. 

In case you were curious, I had my charts' options being set to an angular constant -- which resulted in their sharing of the same object reference in memory.  

Thanks for your assistance and for such a stellar directive.  Looking into this issue at least got me to upgrade to your latest version.  :)

**Comment by maxklenk** [comment]
No problem, I am just happy that it is not a angular-chart bug ;-)
