### ISSUE TITLE
Toggle Legend Option Not Working

### ISSUE THREAD

**Issue by mindontheblink** [GraFiddle/angular-chart#102]
I have been trying to find a way to toggle the legend in 0.3.2.  

http://c3js.org/samples/options_legend.html

This option no longer seems compatible in the chart options for 0.3.2 as far as I can tell.  This was working in 0.2.9.  I wasn't able to find any documentation on this option, and fully-supported c3 API would mean I should be able to do the following:

```
  // chart options
  $scope.options = {
    data: data,
    legend: {
       show: false
    },
    dimensions: {
      first: {
        type: "bar"
      },
      second: {}
    }
  };
```

Thanks in advance.

**Comment by maxklenk** [comment]
For sure you can, please add all c3 specific configurations inside `options.chart`, then it [will work](http://grafiddle.it/5694209793196032).

```JavaScript
// chart options
  $scope.options = {
    data: data,
    chart: {
      legend: {
        show: false
      }
    },
    dimensions: {
      first: {
        type: "bar"
      },
      second: {}
    }
  };
```
