### ISSUE TITLE
Chart not drawing on Chrome version 45

### ISSUE THREAD

**Issue by warapitiya** [GraFiddle/angular-chart#105]
Chat will not draw on chrome version 45 (Latest update)

**Comment by maxklenk** [comment]
Hi @warapitiya, for me on mac everything works fine in the current chrome version 45.
* Could you please provide information about your system (OS, full chrome version number)
* Does the demo work for you http://grafiddle.github.io/angular-chart/ ?
* Please open the console and copy us the errors.

**Comment by warapitiya** [comment]
###System:
* OS : Mac
* Chrome : Version 45.0.2454.85 (64-bit)

Tried on different Mac and Windows machines same happens. But when I move to Firefox it works fine. Also tired on Angular 1.4.0 & 1.4.5

**Comment by maxklenk** [comment]
MMh, it works all right in my browser with the exact same version, but I still don't get if the demo isn't working for you or the integration in your project?
And the error log would be nice to have.

**Comment by maxklenk** [comment]
We were not able to reproduce this bug without additional information about the failing configuration.
