### ISSUE TITLE
some options don't work

### ISSUE THREAD

**Issue by Phisherman** [GraFiddle/angular-chart#108]
Hey,

I've just figured out how to use angular-chart due to the bad documentation and missing examples. 

I want to use a color pattern with a threshold for the gauge chart just like the example on http://c3js.org/samples/chart_gauge.html

Here is my grafiddle: http://grafiddle.it/5657382461898752. What did I wrong?

**Comment by maxklenk** [comment]
Hi @Phisherman,

please provide a pull request or ideas how to improve the documentation. We will link examples as soon as we find time for it.

For your problem checkout this [grafiddle](http://grafiddle.it/5688424874901504).
The dimensions `object` contains the information about which data you want to display and the `chart` object can contain all options you have in c3.js

**Comment by Phisherman** [comment]
Thanks! You helped me a lot.

Some examples like this grafiddle help a lot in understanding how to use your wrapper.
