### ISSUE TITLE
Injecting chart containers

### ISSUE THREAD

**Issue by NastyLucas** [GraFiddle/angular-chart#111]
Hi I'm having a little trouble picking up a directive in angular: when I try to inject it using this function, does it require me to already have the angular chart tag on the page or is there a way around this to inject the data in?

`
angular.element(
		document.getElementById('chart-container-inject')
	)
	.prepend( $compile(
		'<angular-chart options="options" style="height: 500px"></angular-chart>'
	)( $scope ) );
`

Lucas

**Comment by maxklenk** [comment]
Hey @NastyLucas,

perhaps you can explain a little bit more what you want to archive by injecting the chart this way. What worked for me was the following setup:

```JavaScript
$scope.options = someOptions;
$compile(
  angular
    .element( document.getElementById('chart-container-inject'))
    .prepend('<angular-chart options="options" style="height: 500px"></angular-chart>')
)( $scope );
```

**Comment by NastyLucas** [comment]
Oh wow thank you very much I hadn't thought of that approach, I'd been tearing my hair out trying to get that to work properly so thanks for the reply!

**Comment by maxklenk** [comment]
No problem.
