### ISSUE TITLE
Get data on click

### ISSUE THREAD

**Issue by speed-e** [GraFiddle/angular-chart#113]
Hi,
I was looking through your documentation and I can't seem to find how would one handle clicking on a chart? When I click one of the series on the pie chart I would like to drill down deeper into the dataset (loaded dynamically as JSON). How would you catch the part of data that has been selected? I tried using options.state.selected, but that did not work. Any help would be greatly appreciated :)

Thanks!

**Comment by btm1** [comment]
@speed-e you can accomplish this by adding the click event to the "chart" portion of the config object:

```
    		$scope.mychartconfig = {
                 dimensions: {},
    			chart: {
    				data: {
    					onclick: function(d, elem) {
                        //do some stuff
    					}
    				}
    			}	
    		}
```

**Comment by maxklenk** [comment]
@speed-e the posted solution is what you need. Please tell us if you need more support.
