### ISSUE TITLE
Is C3s data.xs supported?

### ISSUE THREAD

**Issue by lbayerl** [GraFiddle/angular-chart#115]
We did not manage to use C3s data.xs attribute: http://c3js.org/reference.html#data-xs
like in this example: http://c3js.org/samples/simple_xy_multiple.html

Grafiddle is here: http://grafiddle.appspot.com/5724313353191424

**Comment by maxklenk** [comment]
Hey @lbayerl,

the `data.xs` attribute can be specified inside the `chart` object of your configuration. I updated your grafiddle by removing a duplicate of the `chart` object and adding the `xs` configuration. I have no experience if the `data.xs` attribute works with json data, but in this grafiddle the option is placed at the right position: http://grafiddle.appspot.com/5685057352105984

**Comment by lbayerl** [comment]
Thanks @maxklenk . You guided me into the right direction. In the end I found that I even don't need the xs attribute in my case. Only thing is to avoid a "breaking" line when one x value has no y-key has a null value. This can be easily achieved by adding connectNull: true to the line attribute within the chart object. 

For everyone who might be interested in the solution, please see this [grafiddle](http://grafiddle.appspot.com/5670405876482048)

You can close this issue. Thanks.
