### ISSUE TITLE
request: function for line chart marker color in dimension configuration

### ISSUE THREAD

**Issue by jcollum** [GraFiddle/angular-chart#116]
I'd like to be able to make a line chart where the color of each marker is dependent on a property in the datapoint. This fiddle does it: http://jsfiddle.net/JedRW/7/

![image](https://cloud.githubusercontent.com/assets/704514/14994923/219de27a-1127-11e6-8550-0d78c5806714.png)

I'm willing to take a shot at it, I just want to make sure this isn't being done (or is done) already.

**Comment by jcollum** [comment]
Figured it out: 

              graphOptions =
                data: datapoints
                dimensions: dims
                chart:

                  data:
                    color: (color, d) ->
                      if d.index? and data[d.index]?
                        return colors[data[d.index].status]
                      else return color

**Comment by maxklenk** [comment]
Great, thanks for sharing your solution with the community.
