### ISSUE TITLE
How to implement on click event on piechart/bar chart using this directive

### ISSUE THREAD

**Issue by vinaynijhawan** [GraFiddle/angular-chart#120]
How to implement onclick event on pie/bar chart using this directive

**Comment by maxklenk** [comment]
Hey, c3js offers an `onclick` event when a user clicks on your data: http://c3js.org/reference.html#data-onclick

Try to use it like this:
```JS
var options = {
  chart: {
    data: {
      onclick: function (d, element) { ... }
    }
  }
}
```

**Comment by vinaynijhawan** [comment]
how we can access this object or scope inside this chart.data.onclick event ?
i want to call one function which is inside the $scope or this.
i am using typescript using angualr js
