### ISSUE TITLE
Chart is generated with black color fill.

### ISSUE THREAD

**Issue by pravinarr** [GraFiddle/angular-chart#123]
Hello,
I am tried to generate a line chart for the data below.

  $scope.options = {
          data: [{
            "id": 0,
            "bestConsistency": 0,
            "classifier1Accuracy": 0,
            "classifier2Accuracy": 70,
            "consistency": 0,
            "noOfRows": 0
        }, {
            "id": 1,
            "bestConsistency": 17,
            "classifier1Accuracy": 87.7,
            "classifier2Accuracy": 0,
            "consistency": 1.7000000000000002,
            "noOfRows": 5
        }, {
            "id": 2,
            "bestConsistency": 20,
            "classifier1Accuracy": 90,
            "classifier2Accuracy": 20,
            "consistency": 20,
            "noOfRows": 50
        }],
        dimensions: {
            id: {
                type: 'line',
                axis: 'x'
            },
            bestConsistency: {
                type: 'line',
                axis: 'y'
            },
            classifier1Accuracy: {
              type: 'line',
                axis: 'y'
            },
            classifier2Accuracy: {
              type: 'line',
                axis: 'y'
            },
            consistency: {
              type: 'line',
                axis: 'y'
            },
            noOfRows: {
              type: 'line',
                axis: 'y'
            }
        }
    };

This is the generated chart
![image](https://cloud.githubusercontent.com/assets/8682635/19616816/6727be42-97d2-11e6-8504-71eb35d6f467.png)

Is something wrong with my configuration ?

Thanks for your help.

**Comment by vinaynijhawan** [comment]
i feel the same issue any help ?

**Comment by maxklenk** [comment]
Looks like you are missing some css, have a look at #74 adding the 

```html
<link rel="stylesheet" href="bower_components/c3/c3.css" />
```

file should help.
