### ISSUE TITLE
Plots don't show up but data set is there

### ISSUE THREAD

**Issue by ctimmins** [GraFiddle/angular-chart#60]
Can't see the actual plots but mouse over shows the data is there and correct

**Comment by maxklenk** [comment]
Please provide a sample in [Plunker](http://plnkr.co/) so we can help you to figure out whats the problem.

**Comment by ctimmins** [comment]
I am having a difficult time re-creating my application in plunker.  I am currently busy with my senior design and other hardware issues, but I would love to solve this issue.  Can I get back to this another time?

**Comment by maxklenk** [comment]
Sure come back at any time, I would be happy to know what issue you have found.
To make it as easy as possible for you to re-create the bug, you can build on top of this [working example](https://jsfiddle.net/maxklenk/r0wep1pm/2/).

**Comment by maxklenk** [comment]
Closed because there was no update for a year.
