### ISSUE TITLE
Is there a way to integrate this with cross filter

### ISSUE THREAD

**Issue by chintamanil** [GraFiddle/angular-chart#66]
I am trying to integrate this with crossfilter for large data sets. Is there a directive for that ?

**Comment by maxklenk** [comment]
I am not aware of any solution that already connects angular-chart to [crossfilter](http://square.github.io/crossfilter/), feel free to build or find one and share it with us.

**Comment by maxklenk** [comment]
Closed because it seams nobody is working on such a plugin at the moment.
