### ISSUE TITLE
Charts is not being refreshed

### ISSUE THREAD

**Issue by tony6636** [GraFiddle/angular-chart#71]
Hi, I use the line chart, I noticed that it works fine if I have e.g. 70 rows. But, if that count is bigger than that, let's say 250, the data is binded only once. If the new data comes via ajax (json) the chart doesn't refresh. Why ?

**Comment by maxklenk** [comment]
I limited the watcher to not doing a deep watch of datasets with more than 100 rows (but this number can be configured https://github.com/maxklenk/angular-chart#watchlimit--integer). For bigger datasets only the number of rows is checked, which should trigger in your case too. I will check that.
For the moment you could increase the watchlimit or update the options to trigger a redrawing.

**Comment by maxklenk** [comment]
Closing for now, as there is no update.
