### ISSUE TITLE
Onselected function. Can't access to selection array

### ISSUE THREAD

**Issue by peibol16** [GraFiddle/angular-chart#82]
I have this issue in develop branch 0.3.0

When I select a bar in a row chart I can't access to full object. I have the following code:

```javascript
chart: {
      data: {
             selection: {
                   enabled: true,
                   multiple: false
              },
              onselected: function(data) {
                    custom code
              }...
```
In custom code section I can´t access to selection array placed in options.state.selected and data not contains full object with category name.

**Comment by maxklenk** [comment]
The `data` you get passed from the `onselected()` function is the same as added to `options.state.selected`, I don't know what additional information you would like to access.

To access all selections you can do the following:
```javaScript
var options = {
  chart: {
    selection: {
      enabled: true,
      multiple: true
    },
    onselected: function(data) {
      console.log(data, options.state.selected);
    }
  },
  ...
}
$scope.options = options;
```

**Comment by peibol16** [comment]
Yes, I get the following object:
```
{
  value: VALUE,
  id: COLUMN_NAME,
  index: X_AXIS_INDEX
}
```
I get y axis value but I want x axis value too.

If my dimension.dataType is category, for example I have 3 bars [apple, orange, banana], when I click on "apple bar" I want X axis value ("apple")  for filter another data in the page.

I opened, previously, an issue in c3 proiect but the solution was not clean. I expect same data as tooltip has when onmouseover event is fired. I don´t know if I forget something to make it works as I expect.

**Comment by maxklenk** [comment]
As you saw in the other response, c3 does not support this functionality. But you are abel to access your data, so you could try to use the `X_AXIS_INDEX` to retrieve the right category from your data.
