### ISSUE TITLE
Add simple example for a working pie chart

### ISSUE THREAD

**Issue by nonZero** [GraFiddle/angular-chart#97]
It is unclear how the options should be used to generate a pie chart.

For example with the following data:

    [
        {title: "Foo", count: 123},
        {title: "Bar", count: 456},
        {title: "Baz", count: 789}
    ]

Any help would be appreciated :-)

**Comment by maxklenk** [comment]
I create an [grafiddle](http://grafiddle.it/5659118702428160) for you. We try to separate the data and the visualisation. Therefor the data contains only an identifier (`first`, `second`,...) and the dimensions object defines what should be display and how you want to name it.

**Comment by nonZero** [comment]
Thank you!

Adding here for future reference:

	{
	  "dimensions": {
	    "first": {
	      "name": "foo",
	      "type": "pie"
	    },
	    "second": {
	      "name": "bar",
	      "type": "pie"
	    },
	    "third": {
	      "name": "baz",
	      "type": "pie"
	    }
	  },
	  data: [{
	    "first": 12,
	    "second": 16,
	    "third": 72
	  }]
	}

**Comment by random-one** [comment]
And I would ask for the same example but for version 0.2.9.
